python/python/python-crash-lab/chap17&18/Project/pizzeria/ll_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
]

python/python/python-crash-lab/chap17&18/Project/pizzeria/pizzas/urls.py
"""Define URL patterns for learning_logs."""

from django.urls import path

from . import views

app_name = 'pizzas'

urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    
    path('pizzas/', views.pizzas, name='pizzas'),
    # Detail page for a single pizza

    path('pizza/<int:pizza_id>/', views.pizza, name='pizza'),
]

python/python/python-crash-lab/chap17&18/Project/pizzeria/pizzas/models.py
from django.db import models


class Pizza(models.Model):
    """A topic the user is learning about."""
    name = models.CharField(max_length=100)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model."""
        return self.name

class Topping(models.Model):
    """Something specific learned about a topic."""
    Pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'toppings'


    def __str__(self):
        """Return a simple string representing the entry."""
        if len(self.name) < 50:
             return f"{self.name[:50]}"
        else:
             return f"{self.name[:50]} ..."

python/python/python-crash-lab/chap17&18/Project/pizzeria/pizzas/views.py
from django.shortcuts import render

from .models import Pizza

def index(request):
    """The home page for meal plans."""
    return render(request, 'pizzas/index.html')


def pizzas(request):
    pizzas = Pizza.objects.order_by('date_added')
    context = {'pizzas': pizzas}
    return render(request, 'pizzas/pizzas.html', context)



def pizza(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.order_by('-date_added')
    context = {'pizza': pizzas, 'toppings': toppings}
    return render(request, 'pizzas/pizza.html', context)

python/python/python-crash-lab/chap17&18/Project/pizzeria/pizzas/templates/pizzas/base.html
<p>
  <a href="{% url 'pizzas:index' %}">pizzas</a> -
  <a href="{% url 'pizzas:pizzas' %}">Pizzas</a>
</p>

{% block content %} {% endblock content %}

python/python/python-crash-lab/chap17&18/Project/pizzeria/pizzas/templates/pizzas/index.html
{ % extends 'learning_logs/base.html' %}
<p>Pizza</p>

{% block content %}
<p>Yummy 🍕 at your doorstep.</p>
{% endblock content %}

python/python/python-crash-lab/chap17&18/Project/pizzeria/pizzas/templates/pizzas/pizza.html
{% extends 'pizzas/base.html' %} {% block content %}
<p>Pizza: {{ pizza.text }}</p>

<p>Toppings:</p>

<ul>
  {% for topping in toppings %}
  <li>
    <p>{{ topping.date_added|date:'M d, Y H:i' }}</p>
    <p>{{ topping.name|linebreaks }}</p>
  </li>
  {% empty %}
  <li>there are no toppings for this pizza yet.</li>
  {% endfor %}
</ul>

{% endblock content %}

python/python/python-crash-lab/chap17&18/Project/pizzeria/pizzas/templates/pizzas/pizzas.html
{% extends 'pizzas/base.html' %} {% block content %}

<p>Pizzas</p>

<ul>
  {% for pizza in pizzas %}
  <li>
    <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza.name}}</a>
  </li>
  {% empty %}
  <li>No pizza have been added yet.</li>
  {% endfor %}
</ul>

{% endblock content %}